### PR TITLE
Fixing issue in Initialize-TestEnvironment (#97)

### LINKED ISSUE #97: Initialize-TestEnvironment function does not support use of ScriptsToProcess parameter in PSD1
The function Initialize-TestEnvironment tries to import the specified module. However, if that module is using the ScriptsToProcess parameter in the PSD1 file, the function throws an error. I have tracked this down to the following line:
https://github.com/dsccommunity/DscResource.Test/blob/75778b90f96df95304950711244bbda3076f9350/source/Public/Initialize-TestEnvironment.ps1#L119

In that case the Import-Module cmdlet returns two modules, resulting in $ModuleUnderTest to become an array instead of a string. All subsequent don't expect this scenario and fail.

The solution is to add Where-Object to the line:
```PowerShell
$ModuleUnderTest = (Import-Module $Module -PassThru -ErrorAction Stop) | Where-Object -FilterScript { $_.Name -eq $Module }
```

Will submit a PR to correct this issue.

### PR DESCRIPTION
**Pull request by ykuijs**
This PR fixes an issue in Initialize-TestEnvironment

- Fixes #97

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.test/98)

### CODE REVIEW

**Review by gaelcolas — APPROVED** [review]
Yeah, that looks good.

**Review by johlju — CHANGES_REQUESTED** [review]
Just a tiny comment.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.test/98#-:-MQwtGYV0nMxOSxYa2fY:ba1zbnl)* status: all files reviewed, 1 unresolved discussion (waiting on @ykuijs)

___
*[source/Public/Initialize-TestEnvironment.ps1, line 119 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.test/98#-MQwswDHAT3e3Bsv568i:-MQwswDIElKviBHEqJGG:b808wl6) ([raw file](https://github.com/dsccommunity/dscresource.test/blob/ceff5c6bb607ee279ece40ac7dc3aeb8aa605524/source/Public/Initialize-TestEnvironment.ps1#L119)):*
> ```
> | Where-Object -FilterScript { $_.Name -eq $Module }
> ```

Could we add a comment to this row so that this isn't removed. Rather would have had a test for this, but sounds like this would need a complex test, so a comment could help to not get a regression.

**Review by ykuijs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.test/98)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[source/Public/Initialize-TestEnvironment.ps1, line 119 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.test/98#-MQwswDHAT3e3Bsv568i:-MQwvVCVCYkztqv6ljqW:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.test/blob/ceff5c6bb607ee279ece40ac7dc3aeb8aa605524/source/Public/Initialize-TestEnvironment.ps1#L119)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> | Where-Object -FilterScript { $_.Name -eq $Module }
> ```

Could we add a comment to this row so that this isn't removed. Rather would have had a test for this, but sounds like this would need a complex test, so a comment could help to not get a regression. 
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.test/98#-:-MQwvcUN4sWJv1sUDrpQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
