### PR TITLE
Migrate Tests to Pester 5

### PR DESCRIPTION
**Pull request by dan-hughes**
#### Pull Request (PR) description

Migrate Unit, QA and Integration tests to Pester 5.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Test/140)

### CODE REVIEW

**Comment by dan-hughes** [comment]
@johlju, when I switch on DocGenerator it complains about being unable to find a type. The type is Pester.OutputTypes and it's a parameter on one of the public functions.

Any idea of a workaround?

**Comment by dan-hughes** [comment]
I think [this](https://github.com/dsccommunity/DscResource.DocGenerator/blob/04ce8534583df019b38be46e308d720db3b8bfb4/source/tasks/Generate_Markdown_For_Public_Commands.build.ps1#L109-L111) may solve the issue. 

I don't quite know how to populate it though. Any ideas?

**Comment by johlju** [comment]
Add `$env:DependentModule` before running the task is one way.

**Comment by johlju** [comment]
Okay so the parameter you pointed out might have been a way to replace this, but I never got around to it:

https://github.com/dsccommunity/SqlServerDsc/blob/85ea1eda6a2d3c3bacd096983d55c99b75dba914/build.yaml#L43-L56

So maybe make an inline task like above that sets the environment variable to the dependent modules to import?

**Comment by johlju** [comment]
It seems there is also this that helps adding the SQL Server types necessary for generating docs when the pipeline runs:
https://github.com/dsccommunity/SqlServerDsc/blob/85ea1eda6a2d3c3bacd096983d55c99b75dba914/azure-pipelines.yml#L40-L55

I think we needed that in the pipeline to remove an older version of SqlServer and SQLPS modules. Won't be needed in this case I think, unless an none or older version of Pester is installed on the build worker. 🤔

**Comment by dan-hughes** [comment]
Thanks. I'll take a look and see if it fixes it. 

Apart from the doc issue, this is ready for review.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 53 of 54 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Test/140)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-hughes)

___
*[`tests/Unit/Private/Set-EnvironmentVariable.Tests.ps1` line 50 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Test/140#-OCO2gN-2p_cJq7R6TxI:-OCO2gN-2p_cJq7R6TxJ:b-24o231) ([raw file](https://github.com/dsccommunity/DscResource.Test/blob/9587067e01795e6dc4dd8520994bcfc243626537/tests/Unit/Private/Set-EnvironmentVariable.Tests.ps1#L50)):*
> ```PowerShell
> 
> Describe 'Set-EnvironmentVariable' -Tag 'Private' {
>     # BeforeAll {
> ```

Should we comment why this code is commented. Guessing there is an issue actually testing this?
___
*[`tests/Unit/Private/Set-PSModulePath.Tests.ps1` line 1 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Test/140#-OCO2q0fEaJPkblaHzCq:-OCO2q0fEaJPkblaHzCr:b-u1qpy3) ([raw file](https://github.com/dsccommunity/DscResource.Test/blob/9587067e01795e6dc4dd8520994bcfc243626537/tests/Unit/Private/Set-PSModulePath.Tests.ps1#L1)):*
> ```PowerShell
> # $ProjectPath = "$PSScriptRoot\..\..\.." | Convert-Path
> ```

Why is this code commented? Guessing the file is needed, should we track this test in an issue so it get fixed in another PR? 
___
*[`source/Public/Invoke-DscResourceTest.ps1` line 137 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Test/140#-OCO1N890bxh4ycPrW0k:-OCO1N890bxh4ycPrW0l:b52ibvv) ([raw file](https://github.com/dsccommunity/DscResource.Test/blob/9587067e01795e6dc4dd8520994bcfc243626537/source/Public/Invoke-DscResourceTest.ps1#L137)):*
> ```PowerShell
>         [Parameter(ParameterSetName = 'ByProjectPath')]
>         [System.String]
>         $MainGitBranch = 'main',
> ```

I think this need to be `master` unfortunately to not break older not yet converted pipeline (those not yet setting the parameter in azure-pipelines.yml). :thinking:

**Review by johlju — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Test/140)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

___
*[`tests/Unit/Private/Set-EnvironmentVariable.Tests.ps1` line 50 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Test/140#-OCO2gN-2p_cJq7R6TxI:-OCTkuTE-uIT79-IAMrZ:bk2581f) ([raw file](https://github.com/dsccommunity/DscResource.Test/blob/9587067e01795e6dc4dd8520994bcfc243626537/tests/Unit/Private/Set-EnvironmentVariable.Tests.ps1#L50)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

I missed going back to this one. I'll at it again
</blockquote></details>

Not following. You want to send in a commit for this or track it in a issue so this gets fixed in another PR? :thinking:

**Comment by dan-hughes** [comment]
> > Reviewed 3 of 3 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Test/140)_ status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes)
> 
> _[`tests/Unit/Private/Set-EnvironmentVariable.Tests.ps1` line 50 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Test/140#-OCO2gN-2p_cJq7R6TxI:-OCTkuTE-uIT79-IAMrZ:bk2581f) ([raw file](https://github.com/dsccommunity/DscResource.Test/blob/9587067e01795e6dc4dd8520994bcfc243626537/tests/Unit/Private/Set-EnvironmentVariable.Tests.ps1#L50)):_
> 
> Previously, dan-hughes (Daniel Hughes) wrote…
> Not following. You want to send in a commit for this or track it in a issue so this gets fixed in another PR? 🤔

I was going to go and spend a little more time on this one, I think I converted it but it had some issues testing cross platform.

If you want to merge and capture this via an issue I'm good with that too.

**Comment by johlju** [comment]
@dan-hughes can you create separate issues for those tests that have missing or incomplete code and I merge this PR.

**Review by johlju — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Test/140#-:-OCTvjT-07Fx6PIbPLrV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Pull request merged**
