### PR TITLE
Added E2E test type to Initialize-TestEnvironment

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR adds E2E test type to `Initialize-TestEnvironment` and `Restore-TestEnvironment` for use by xPSDesiredStateConfiguration.

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.test/49)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@gaelcolas , @johlju - Reconsidering this one: Instead of calling E2E, do we want to call it "All" or something to that effect? Behaviour would be the same (load the module and init the LCM).

**Comment by johlju** [comment]
@PlagueHO Looks good but the tests fail

**Comment by PlagueHO** [comment]
Tests now passing @johlju

**Comment by PlagueHO** [comment]
@johlju - should just need one final review.

**Pull request merged**
