### PR TITLE
Test 'Common Tests - Module Manifest' no longer fails when class-based resource exist

### LINKED ISSUE #66: ModuleManifest.common.Tests.ps1 is failing with 'ParameterBindingValidationException'
In the file [ModuleManifest.common.Tests.ps1](https://github.com/dsccommunity/DscResource.Test/blob/master/source/Tests/QA/ModuleManifest.common.Tests.ps1) a variable is used that is not declared: Line 44  $moduleRootFilePath.

```
    [-] Error occurred in Describe block 0ms
      ParameterBindingValidationException: Cannot bind argument to parameter 'FilePath' because it is an empty string.
      at <ScriptBlock>, C:\Git\JeaDsc\output\RequiredModules\DscResource.Test\0.12.1\Tests\QA\ModuleManifest.common.Tests.ps1: line 44
      at DescribeImpl, C:\Git\JeaDsc\output\RequiredModules\Pester\4.10.1\Functions\Describe.ps1: line 213
```

Another minor issue is the parameter block. None of the parameters is marked as mandatory which is pretty likely not true.

### PR DESCRIPTION
**Pull request by raandree**
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.test/67)

### CODE REVIEW

**Comment by raandree** [comment]
Sorry @PlagueHO, I always forget this :(

**Comment by PlagueHO** [comment]
Hi @raandree - Unfortunately the CI build agents that this pipeline uses have been deprecated. This is causing the build to fail. Have submitted an issue to fix it (https://github.com/dsccommunity/DscResource.Test/issues/68) and will submit a PR. Once that is through we'll be able to merge yours. Sorry about that.

**Comment by raandree** [comment]
Thanks, @PlagueHO. Just wondering, how did you migrate all the other DSC resources to the [Sampler](https://github.com/gaelcolas/Sampler) considering that at least this test did not work?

I found two similar projects:
- https://github.com/dsccommunity/DscResource.Test
- https://github.com/PowerShell/DscResource.Tests

The one in the PowerShell org looks much larger so I am wondering why another repo has been created. Or do I miss something here?

**Comment by johlju** [comment]
@raandree there are no class-based resources in any repo that has been converted. Also the DscResource.Tests repo has been split up into three repos; DscResource.Test, DscResource.DocGenerator, and DscResource.AnalyzerRules. This was done to support the new pipeline in Sampler. There are still functionality that should be brought over.

**Comment by raandree** [comment]
Thanks, @johlju for explaining. I have done the changes and it looks better now.

**Comment by PlagueHO** [comment]
@raandree - yep, what @johlju said :grin:

I never got an opportunity to use Class based resources in any of the modules I maintained because early on they needed to be compatible with PS 4.0 which didn't support them. That has changed now of course... but old habits...

It also felt cleaner to only use either all class based or all MOF based in a single resource module, but that wasn't a strict requirement - just something I tended to do.

**Pull request merged**
