### PR TITLE
Updating Localization Tests to add exclusion filter

### PR DESCRIPTION
**Pull request by gaelcolas**
Hi @X-Guardian, I've finally updated the localization tests.
Could you please have a look and see if it makes sense?

Can you also run it against a compiled version of ActiveDirectoryDsc to see if that seems to work?

If you have the built module locally in your path you can do this:
```
Invoke-DscResourceTest -Module ActiveDirectoryDsc -Tag 'Common Tests - Validate Localization' -ExcludeModuleFile 'Modules','Templates'
```
You can also run by Project path:
```
Invoke-DscResourceTest -ProjectPath C:\src\ActiveDirectoryDsc -Tag 'Common Tests - Validate Localization' -ExcludeModuleFile 'Modules','Templates'
```

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.test/30)

### CODE REVIEW

**Comment by X-Guardian** [comment]
Hi @gaelcolas, if I run `Invoke-DscResourceTest` in a new PowerShell session, after runnning `.\build.ps1 noop`, I get the following error:
```
Unable to find type [Pester.OutputTypes].
At \\nas01\data\users\simon\documents\GitHub\X-Guardian\ActiveDirectoryDsc\output\RequiredModules\DscResource.Test\0.5.3\DscResource.Test.psm1: 
1161 char:9
+         [Pester.OutputTypes]
+         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Pester.OutputTypes:TypeName) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TypeNotFound
```
Manually importing the `Pester` module resolves the issue.

**Comment by X-Guardian** [comment]
The updated test is failing, with the following error:
```
     [-] Should have en-US localization string resource file \\nas01\data\users\simon\documents\GitHub\X-Guardian\ActiveDirectoryDsc\output\ActiveDirectoryDsc\5.0.0\en-US\ActiveDirectoryDsc.strings.psd1 29ms
        Expected $true, because the string resource file \
        as01\data\users\simon\documents\GitHub\X-Guardian\ActiveDirectoryDsc\output\ActiveDirectoryDsc\5.0.0\en-US\ActiveDirectoryDsc.strings.psd1 must exist in the localization folder en-US, but got $false.
        99:                 Test-Path -Path $LocalizationFile | Should -BeTrue -Because "the string resource file $LocalizationFile must exist in the localization folder en-US"
        at <ScriptBlock>, \\nas01\data\users\simon\documents\GitHub\X-Guardian\ActiveDirectoryDsc\output\RequiredModules\DscResource.Test\0.5.3\Tests\QA\Localization.common.Tests.ps1: line 99
```

It is trying to find a strings file for the root module psm1 file, which isn't correct.

**Comment by X-Guardian** [comment]
Also, it is now excluding all modules with those parameter options, but `ActiveDirectoryDsc` has an embedded module which needs testing (`ActiveDirectoryDsc.Common.psm1`) so I currently need to run it without the exclude filter. How can this cope when you might have a mix of embedded modules and external modules?

**Comment by X-Guardian** [comment]
Thinking about it, there will definitely be a mix of embedded modules. The external `DscResource.Common` module, containing `Test-DscParameterState` etc and the embedded `ActiveDirectoryDsc.Common` containing the custom functions for the module, `Find-DomainController` etc.

**Comment by X-Guardian** [comment]
How about we separate these into different folders in the build output? `Modules\InternalModules` and `Modules\ExternalModules` for example. Exclude filters can then target `Modules\ExternalModules`.

**Comment by gaelcolas** [comment]
Thanks for testing.
The issue importing DscResource.Test is because Pester is not in RequiredModules, but in ExternalModuleDependencies.
I will be able to fix that, when the Sampler `pack` task is capable of resolving recursive dependencies.
For now, as you found out, we need to have Pester imported before being able to import DscResource.Test

**Comment by gaelcolas** [comment]
> It is trying to find a strings file for the root module psm1 file, which isn't correct.
Actually, that's intended and should be tested.
That said, we should probably double check the file is not empty before testing Localization though, I'll add that.

**Comment by gaelcolas** [comment]
The exclude parameter was to show you an example, to illustrate the capability.
In your case, you probably don't want to exclude anything, and you can also be more specific (the exclude is a relative path, you could have `Modules/DscResource.Common` for instance).
I'd rather include everything by default, and the module authors will selectively exclude as they see fit (i.e. when using `DscResource.Common`).

**Comment by gaelcolas** [comment]
Alright, this looks good to me and I added checks for excluding empty PSM1 or PSM1 that are not defining any function.
That should cover most cases, but you should also remove your ActiveDirectory.psm1 from your source folder (and its reference in the RootModule key of the Module Manifest).

**Pull request merged**
