### PR TITLE
HQRM tests support Pester 5

### LINKED ISSUE #75: HQRM test should be converted to support both Pester 4 and Pester 5

### PR DESCRIPTION
**Pull request by johlju**
This PR make it possible for repos to move over to Pester 5 by supporting HQRM tests in Pester 5. A repo must opt-in to running test in Pester 5 by changing the build configuration (see comment below), or run each test individually in their own pipeline. The task that is introduced here is made to work with Sampler.

This PR is tested against both Pester 4 and Pester 5.

- Fixes #75 

## Pester 5 
FileSystemDsc PASSES locally in WPS and PS7 (must be run in WPS in the pipeline to not skip tests). Using branch here: https://github.com/dsccommunity/FileSystemDsc/pull/13, resolved dependencies after which I copied in the new version of DscResource.Test.

To two tests that didn't run was what was excluded by `ExcludeTag`; `Common Tests - New Error-Level Script Analyzer Rules`
In PS7 the two test that was skipped can only be run in WPS. Pipeline must use WPS.

PS7:
```
Tests completed in 9.28s
Tests Passed: 257, Failed: 0, Skipped: 2 NotRun: 2
```
WPS: 
```
Tests completed in 9.25s
Tests Passed: 259, Failed: 0, Skipped: 0 NotRun: 2
```

## Pester 4 
xWebAdministration PASSES locally in WPS (Pester 4 tests do not work in PS7). Cloned latest xWebAdministration and resolved dependencies after which I copied in the new version of DscResource.Test.

```
Tests completed in 101.18s
Tests Passed: 1545, Failed: 0, Skipped: 66, Pending: 0, Inconclusive: 0
```

### Added

- Added build task `Invoke_HQRM_Tests` and `Fail_Build_If_HQRM_Tests_Failed`.
- Added meta build task `Invoke_HQRM_Tests_Stop_On_Fail` that runs both
  build tasks `Invoke_HQRM_Tests` and `Fail_Build_If_HQRM_Tests_Failed`
  in correct order.
- New QA (HQRM) tests for Pester 5 was added that will only run if Pester 5.1
  is used by the test pipeline.
- Added (converted) HQRM test for Pester 5
  - Added `Changelog.common.v5.Tests.ps1`
  - Added `ExampleFiles.common.v5.Tests.ps1`
  - Added `FileFormatting.common.v5.Tests.ps1`
    - The individual test for checking BOM on markdown files was remove
      and replaced by a test that checks for BOM on all text files (code,
      configuration, and markdown). That also replaced the Pester 4 tests
      `ModuleFiles.common.v4.Tests.ps1` (that only checked for BOM on
      `.psm1`files), and `ScriptFiles.common.v4.Tests.ps1` (that only
      checked for BOM on `.ps1` files). No changes were made to the
      Pester 4 tests, just the Pester 5 tests.
  - Added `MarkdownLinks.common.v5.Tests.ps1`
  - Added `ModuleManifest.common.v5.Tests.ps1`
  - Added `ModuleScriptFiles.common.v5.Tests.ps1`
    - Contain the converted Pester 4 tests from `Psm1Parsing.common.v4.Tests.ps1`.
  - Added `PSSAResource.common.v5.Tests.ps1`
    - Any test that is excluded by using Pester `ExcludeTag` under the key
      `DscTest:` will now be silently excluded due to how Pester does _Discovery_.
  - Added `PublishExampleFiles.v5.Tests.ps1`
  - Added `ResourceSchema.common.v5.Tests.ps1`
- Added public function `Get-DscResourceTestContainer` which returns a Pester
  container for each available Pester 5 HQRM test.

### Changed

- Renamed all existing QA (HQRM) tests to `*.v4.Tests.ps1*` and made
  them not run if test pipeline is using Pester 5.
- The function `Get-TextFilesList` can now take an optional parameter
  `FileExtension` to only return those files, e.g. `@('.psm1')`. This
  makes the function `Get-Psm1FileList` obsolete.
- `Get-DscResourceTestContainer`
  - Changed to support the new Pester 5 HQRM tests, and code for an older
    Pester 5 Beta iteration was removed.

This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.test/91)

### CODE REVIEW

**Comment by johlju** [comment]
Send in draft to get feedback. Will do the rest of the tests before I take this out of draft.

**Comment by johlju** [comment]
A repo can opt-in to run HQRM test in Pester 5 by changing the build configuration. An example below, but this need to be documented,

```yaml
BuildWorkflow:
  '.':
    - build
    - test
 
  hqrmtest:
    - Invoke_HQRM_Tests_Stop_On_Fail

DscTest:
  Pester:
    Configuration:
      Filter:
        Tag:
        ExcludeTag:
          - Common Tests - New Error-Level Script Analyzer Rules
      Output:
        Verbosity: Detailed
  Script:
    ExcludeSourceFile:
      - output
    ExcludeModuleFile:
      - Modules/DscResource.Common
    MainGitBranch: main
```

**Comment by johlju** [comment]
If this PR is approved I will update the documentation on how the build task works, what to configure in build configuration, documentation how to run tests individually, and required and optional parameters in scripts.

**Comment by johlju** [comment]
Run in the Pester 5 tests for SqlServerDsc (in WPS):

```
Tests completed in 302.48s
Tests Passed: 8157, Failed: 4, Skipped: 0 NotRun: 76
```

Failed tests are required rules that now are correctly run for Pester 5 but not for Pester 4 (issue #95).

**Comment by johlju** [comment]
@gaelcolas this is ready for review again.

**Comment by johlju** [comment]
What is left now is the fix for Aliases. Aliases are currently not exported correctly.

**Comment by gaelcolas** [comment]
yeah, we can rework the aliases in another PR, I don't think there's any quick fix we can do here.

**Comment by johlju** [comment]
WOrking on a quick fix now. Give me an hour.

**Review by gaelcolas — APPROVED** [review]
looks Good to me, LGTM!

Later we'll need:
- Export aliases and move aliases definition to Suffix.ps1
- Move functions to public but avoid conflicts
- Remove the -Verbose in tests

**Review by gaelcolas — APPROVED** [review]

**Pull request merged**
