### PR TITLE
HQRM: Only target source module for PSSA and MarkdownLinks

### LINKED ISSUE #57: Update tests to only run against either built module or the source files (not both)
### Against source
- Localization test should only target source.
- MarkdownLinks test should only target source.
- "Common Tests - PS Script Analyzer on Resource Files" test should only target source.  No reason to run PSScriptAnalyzer on the built module.

### Against built-module

No changes at this time

### PR DESCRIPTION
**Pull request by dan-hughes**
#### Pull Request (PR) description
Update PSSAResource and MarkdownLinks to only target source files.

#### This Pull Request (PR) fixes the following issues

- Fixes #57

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Test/137)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Test/137)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Comment by johlju** [comment]
I wonder why I wrote in the issue "Resource Files test should only target source". I wish I wrote the reason. Before merging this, are we sure this is the best way of testing these in Source and not what actually was built och will be published? 🤔
I'm starting to question myself here - testing it in both location is not ideal at least, so that will this PR fix 🙂 

@dan-hughes do you have any thoughts if there are better to test MOF-resources in either Source or built-module? 🤔

**Comment by dan-hughes** [comment]
From a test writing and issue finding perspective it's easier to test against the source files as each resource uses the same structure and it's a 1 to 1 mapping.

I've not looked at 'how' Sampler assembles the individual files into a module, but if Sampler has it's own unit tests and all the source files have passed HQRM is there any benefit of checking them again?

**Comment by johlju** [comment]
> I've not looked at 'how' Sampler assembles the individual files into a module

Sampler calls ModuleBuilder. When ModuleBuilder is called it just copies the entire DSCResources folder to the root of the builtModule. It is configured in build.yaml:

https://github.com/dsccommunity/SqlServerDsc/blob/5677cd5b933d2fce2205fe1c048c24ac5e813254/build.yaml#L59-L60

So there are no tests for this in Sampler or any other code in Sampler. 

> ... all the source files have passed HQRM is there any benefit of checking them again?

No it is not. My thought if we would just test them in the builtModule. 

But let's go with you comment "From a test writing and issue finding perspective it's easier to test against the source files as each resource uses the same structure and it's a 1 to 1 mapping" and merge this 🙂 If there is a downside we can always change in the future. 🙂

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Test/137#-:-O8l0F4i2ZGJSdU7JvKF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Comment by dan-hughes** [comment]
Maybe some ideas from others in the community can be used to define the QA tests that will be needed when Pester 6 arrives.

It would be a good time to make some larger changes as when other modules are converted to Pester 6 any updates/changes to HQRM would not be too significant seeing as it will be a larger than normal changeset anyway.

**Pull request merged**
