### PR TITLE
Localization.common.Tests: Fix Error When DSCResources or Modules Folders don't Exist

### PR DESCRIPTION
**Pull request by X-Guardian**
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.test/29)

### CODE REVIEW

**Comment by gaelcolas** [comment]
Discussing this with @X-Guardian on slack but I'd like to change slightly what we're testing on this on.
I'd rather make sure each PSM1 is using LocalizedData, so the first few lines would look like this:
```PowerShell
Describe 'Common Tests - Validate Localization' -Tag 'Common Tests - Validate Localization' {
    $moduleFiles = @(Get-Psm1FileList -FilePath $ModuleBase | WhereModuleFileNotExcluded)
    if ($SourcePath)
    {
        $moduleFiles += Get-Psm1FileList -FilePath $SourcePath | WhereSourceFileNotExcluded
    }
```

Then resolve the en-us and other language folders based on those files.

**Comment by gaelcolas** [comment]
I'm working on this, will submit a new PR shortly (with a couple of other fix too).

**Comment by johlju** [comment]
@gaelcolas then we won't catch if a contributor sends in a new resource or module and forget about localizing. The test is meant to make sure there are localization in all resources and modules.

> I'd rather make sure each PSM1 is using LocalizedData

This is already catched if the module does not contain `$script:localizedData` the tests fail because it can't match the localized strings. But there could be yet another test to more clearly show that's the problem.

**Comment by gaelcolas** [comment]
@johlju Using PSM1 will still catch those.
Please check #30 as it should accommodate the same scenarios.

**Comment by johlju** [comment]
> @johlju Using PSM1 will still catch those.
> Please check #30 as it should accommodate the same scenarios.

If the tests are not loosing functionality I'm all for it. :)

**Comment by gaelcolas** [comment]
I've merged #30, closing this one, thanks.

**Pull request closed without merging**
