### PR TITLE
Changed Clear-DscLcmConfiguration to Public

### PR DESCRIPTION
**Pull request by PlagueHO**
### Changed

- Added LICENSE (fixes [Issue #41](https://github.com/dsccommunity/DscResource.Test/issues/41)).
- Added standard badges to README.MD (fixes [Issue #43](https://github.com/dsccommunity/DscResource.Test/issues/43)).

### Changed

- Changed module manifest to include Tags, ProjectUri, LicenseUri, Logo
  and changed AliasesToExport to empty (fixes [Issue #42](https://github.com/dsccommunity/DscResource.Test/issues/42)).
- Changed Clear-DscLcmConfiguration to a public function so it can be called
  directly by resource modules (fixes [Issue #40](https://github.com/dsccommunity/DscResource.Test/issues/40)).
- Updated CI triggers to run on PRs against master branch and also run
  against all branches.

### Removed

- Removed Deploy.PSDeploy.ps1 because it is not used (fixes [Issue #44](https://github.com/dsccommunity/DscResource.Test/issues/44)).
- Removed commented out code from DscResource.Test.psm1
  file (fixes [Issue #45](https://github.com/dsccommunity/DscResource.Test/issues/45)).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.test/46)

### CODE REVIEW

**Comment by johlju** [comment]
When you merge this, add something of this `\s?(add|feature|minor)` in the squash description so it raises minor version? I forgot that when I merged the previous PR.

**Comment by PlagueHO** [comment]
Doh! I missed this comment! :(

**Comment by johlju** [comment]
We learn by the mistakes :p We fix that on the next merge (squash) 😄 
Do you release a new version?

**Comment by gaelcolas** [comment]
I recommend doing this when you create your new branch. If you will add a feature, call the branch f/<something>.
If it's a fix, call it fix/<something>

**Comment by PlagueHO** [comment]
I had a commit starting with "Added" anyway. So it was OK this time.

**Comment by gaelcolas** [comment]
No biggie but the test for that function should probably be moved to `tests/Unit/Public/` as well (it's purely for consistency sake and making it easier on humans).

**Comment by PlagueHO** [comment]
I did that in a subsequent PR (the one where I added the new test type). :)

**Pull request merged**
