### PR TITLE
HQRM: Add QA test for class-based localization

### LINKED ISSUE #125: HQRM test for localization does not handle class-based resources
#### Details of the scenario you tried and the problem that is occurring
When having localization files for a class-based resource the HQRM test for [localization](https://github.com/dsccommunity/DscResource.Test/blob/main/source/Tests/QA/Localization.common.v5.Tests.ps1) the tests does not report on unused or missing localization strings.

#### Steps to reproduce the problem
Run HQRM test on class-based resources where it is known that there are localization strings that are missing.

#### Expected behavior
Able to correctly fail pipeline if there is an issue with localization strings (missing or unused).

#### Current behavior
Does not fail the pipeline.

#### Suggested solution to the issue
Add a new HQRM tests to test localization for class-based resources.

#### The operating system the target node is running
n/a

#### Version and build of PowerShell the target node is running
n/a

#### Version of the module that was used
n/a

### PR DESCRIPTION
**Pull request by dan-hughes**
#### Pull Request (PR) description
Adds a HQRM test to check missing or extra localization strings. 

#### This Pull Request (PR) fixes the following issues

- Fixes #125 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Test/133)

### CODE REVIEW

**Comment by dan-hughes** [comment]
@johlju, can you give this a once over please? I just ran it on `DnsServerDsc` and it has found some discrepancies. This started as a copy + paste of the non-class Localization Tests which I then updated to catch all the classes.

It's a little rough but I wanted to get eyes on it for general direction before spending too much time going down this current direction.

**Comment by dan-hughes** [comment]
@johlju, I just tested this on SqlServerDsc and DnsServerDsc, found an edge case in SqlServerDsc which is now catered for.

**Comment by johlju** [comment]
Awesome work! It looks like it works as intended. Just a few notes below.

Actually in SqlServerDsc - and using it as an example...

`$script:localizedData` should check against `en-US/SqlServerDsc.strings.psd1`
`$this.localizedData` should check against resources' own strings file

If it is `$script:localizedData` like in `004.StartupParameters.ps1` that is not a class-based resource, just a PowerShell class it should be allowed to use `$script:localizedData`. In this case I think the tests need to read from the `en-US/SqlServerDsc.strings.psd1` to evaluate strings. We can only evaluate that the string in the code actually is a resource key in the strings file. _If you just want to do class-based resources in this PR then this could be a future PR. Maybe it is part of evaluate strings in private and public functions._ 🤔

Class-based resources that do have `$script:localizedData` we could either see as above, if using `$script:localizedData` it shoukd be checked against `en-US/SqlServerDsc.strings.psd1` if the resource key exist, and if they also have `$this.localizedData` they are evaluated against the resources' own strings file. I think it should be okay to have either `$this.localizedData` or `$script:localizedData`.  🤔 

Currently the class in `002.DatabasePermission.ps1` is not a class-based resource but a class with DSC properties used as a CIM instance the is passed to the Permission parameter of the class-based resource `SqlDatabasePermission`. The file `002.DatabasePermission.ps1` have `$script:localizedData`, and it it can't (easily) implement `$this.localizedData` unless there is maybe a base class for that purpose too. So I used `$script:localizedData` to get localized string that are loaded when module is imported.

Just a few things to consider. 🙂

**Comment by johlju** [comment]
After sleeping on this I think we can handle the above scenarios in two different tests.

### Built Module

This will cover all private and public command, all types of classes and also if a module uses localized strings in prefix.ps1 and suffix.ps1. 

1. Search for `$script:localizedData` in the entire built module script file and check them against the built `en-US/<module>` for existens. 
2. Then search all string resource keys in the `en-US/<module>` and check them for existens in the built script module. 

### Class-based resource in built module

1. Check for `$this.localicedData` for each built class-based resource in built module and compare against its own resources' strings file. 
2. Then search all string resource keys in the resources' strings file and check them for existens in the built class-based resource. 

There is an edge case here, but I suggest we skip this for now. 

It is possible to override a resource key of a derived class, e.g. ResourceBase. Those string resource keys that are overridden will obviously not be in the built class-based resource. It is not used as far as I know, but it is possible - or at least it was possible, I haven't tried it for a long time. 🙂  I’m not sure we can handle that edge case as easily. It would mean that we need to read the possible resource keys of a derived class (that can be in an entire other module) and make those allowed resource keys for the class-based resource too.

**Comment by dan-hughes** [comment]
@johlju, after reading and digesting this I think I understand what needs to be done. 

Any ideas for the filenames for these (I assume) two QA tests?

I'll take into account the overriding of localization strings in classes as it may be easier to consider this up front instead of adding it on later.

**Comment by johlju** [comment]
> Any ideas for the filenames for these (I assume) two QA tests?

Suggest the names:

- `Localization.builtModule.v5.Tests.ps1` or `Localization.module.v5.Tests.ps1`
  - Handles `$script:localizedData` in the entire built module script file 
- `Localization.classResource.v5.Tests.ps1`
  - Handles `$this.localizedData` for each built class-based resource in the built module

**Comment by dan-hughes** [comment]
@johlju, is `Localization.builtModule.v5.Tests.ps1` replacing `Localization.common.v5.Tests.ps1`?

**Comment by johlju** [comment]
Hmm, I was wrong in thinking the existing localization test was only testing localization in MOF-based resources. It seems it is also testing the built module if I'm reading the code correctly. So either we keep "common" as is and don't add the "builtModule" one, or we rename "common" to "mofResources" and change it to only look for .psm1 files in the DSCResources. The later we have more leeway to change localization testing for built module without the need to think of the MOF-resources testing. The testing is also split up and we could more easily filter out some tests from running in build configuration. 🤔

Since you looking at this I leave it to you to decided the best way. 😊

**Comment by dan-hughes** [comment]
@johlju, I think I have this sorted now. 

I ran against SqlServerDsc and it picked up everything expected. File naming may need to change.

**Comment by dan-hughes** [comment]
@johlju it would be good to get this and #137 reviewed and merged to test on the preview branch.

**Review by johlju — COMMENTED** [review]
> Reviewed 5 of 8 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Test/133)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

___
*[`source/Tests/QA/Localization.builtModule.v5.Tests.ps1` line 17 at r5](https://reviewable.io/reviews/dsccommunity/DscResource.Test/133#-O8gw34mBcjtbXSPVlgO:-O8gw34mBcjtbXSPVlgP:b-h1woxx) ([raw file](https://github.com/dsccommunity/DscResource.Test/blob/b7dd32f95b63f281fb847bceba8941ffa8e2b543/source/Tests/QA/Localization.builtModule.v5.Tests.ps1#L17)):*
> ```PowerShell
> param
> (
> ```

Extra blank line here

**Review by dan-hughes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Test/133)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[`source/Tests/QA/Localization.builtModule.v5.Tests.ps1` line 17 at r5](https://reviewable.io/reviews/dsccommunity/DscResource.Test/133#-O8gw34mBcjtbXSPVlgO:-O8iBnpt-R4np6sSp-Or:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.Test/blob/b7dd32f95b63f281fb847bceba8941ffa8e2b543/source/Tests/QA/Localization.builtModule.v5.Tests.ps1#L17)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Extra blank line here
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Test/133#-:-O8kP83T6fnfnQAbF4nh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Comment by johlju** [comment]
Merging this and then we can see if there is any issues that need to be handled by using it in repos before we push a full release. 🙂

**Pull request merged**
